### ISSUE TITLE
Open VSX

### ISSUE THREAD

**Issue by noraj** [Rpinski/vscode-shebang-snippets#8]
Hi can you push your extension to https://open-vsx.org/ in addition to VSCode Market Place so people using the FLOSS version could install it too?

I wrote [an article](https://blog.raw.pm/en/FLOSS-version-of-vscode-and-extensions-gallery/) on the subject.

**Comment by philoserf** [comment]
https://github.com/HaaLeo/publish-vscode-extension

**Comment by LucasSymons** [comment]
would love to see this as well, I miss my snippets

**Comment by tigsikram** [comment]
Here's further context:

Unfortunately, as Microsoft prohibits usages of the Microsoft marketplace by any other products or redistribution of `.vsix` files from it, in order to use VS Code extensions in non-Microsoft products, we kindly ask that you take ownership of the VS Code extension namespace in [Open VSX](https://open-vsx.org/) and publish this extension on Open VSX.

## What is Open VSX? Why does it exist?

Open VSX is a vendor neutral alternative to the MS marketplace used by most other derivatives of VS Code like [VSCodium](https://vscodium.com/), [Gitpod](https://www.gitpod.io), [OpenVSCode](https://github.com/gitpod-io/openvscode-server), [Theia](https://theia-ide.org/)-based IDEs, and so on.

You can read on about Open VSX at the Eclipse Foundation's [Open VSX FAQ](https://www.eclipse.org/legal/open-vsx-registry-faq/).

## How can you publish to Open VSX?

The docs to publish an extension can be found [here](https://github.com/eclipse/openvsx/wiki/Publishing-Extensions). This process is straightforward and shouldn't take too long. Essentially, you need an authentication token and to execute the `ovsx publish` command to publish your extension. There's also [a doc](https://github.com/open-vsx/publish-extensions/blob/master/docs/direct_publish_setup.md) explaining the whole process with an example GitHub Action workflow.

**Comment by Rpinski** [comment]
My apologies for not replying all the time on this topic - I didn't have much time for the side-projects in the last years.
I understand that publishing to Open VSX would make sense and will take a look at the registration process.

**Comment by Rpinski** [comment]
I've published the last official release of Shebang Snippets (0.1.4) to Open-VSX:

https://open-vsx.org/extension/rpinski/shebang-snippets

Currently I'm waiting for getting ownership of the namespace to remove the warning on extension page.
