### ISSUE TITLE
The update for Shebang Snippets extension introduces executable code, which is not present in the currently installed version. Please review the extension and update it manually.

### ISSUE THREAD

**Issue by douniwan5788** [Rpinski/vscode-shebang-snippets#81]
executable code?

**Comment by Rpinski** [comment]
Before 1.0 this extension has been a snippet package, containing only some JSON files with snippet definitions. Since release 1.0 it has become a full editor extension accessing VS Code's API and therefore containing TypeScript code (as most usual VS Code extensions do).

VS Code has detected this change and then shows this warning for security reasons. But for the Shebang Snippets extension this change is intentional.
